name: Ubuntu VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ubuntu environment
        run: |
          sudo apt update && sudo apt install -y wget curl
          nohup bash -c "while true; do echo Running Ubuntu VPS; sleep 30; done" &
      
      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xvzf ngrok-v3-stable-linux-amd64.tgz
          sudo mv ngrok /usr/local/bin/

      - name: Start Ngrok
        run: |
          ./ngrok authtoken <Your_Ngrok_Auth_Token>
          nohup ./ngrok http 80 &
          sleep 5
          curl -s http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
